enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[proton-vpn]
enabled = true
app-name = "proton-vpn"
rv-brand = "hoodles"
riplib = true
arch = "both"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonvpn.android"

[wps-office-morphe]
enabled = false
app-name = "wps-office"
rv-brand = "hoodles"
build-mode = "apk"
riplib = true
arch = "both"
version = "11.24"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf"
archive-dlurl = "https://archive.org/download/geologically/apks/cn.wps.moffice_eng"

[solid-explorer-morphe]
enabled = true
app-name = "solid-explorer"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"

[smart-launcher-6-morphe]
enabled = true
app-name = "smart-launcher-6"
rv-brand = "hoodles"
build-mode = "apk"
arch = "all"
version = "6.6 build 002 patch 1"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/ginlemon.flowerfree"

[cam-scanner]
enabled = true
app-name = "cam-scanner"
rv-brand = "hoodles"
build-mode = "apk"
arch = "all"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.intsig.camscanner"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator"
